# Generated by Django 4.2.30 on 2026-08-30 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planner", "0003_shifttemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="image",
        ),
        migrations.AddField(
            model_name="shift",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scheduled_shifts",
                to="planner.shifttemplate",
            ),
        ),
    ]
